### ISSUE TITLE
你好怎么把Masonry放到自己的项目，像你的demo一样

### ISSUE THREAD

**Issue by yumengbdw** [saitjr/MasonryDemo#1]
我尝试github上的在pch文件里面先定义一个宏没效果

**Comment by saitjr** [comment]
如果是放到里面的话，下载，然后在使用的时候#import "Masonry.h"
如果是要全局引用，就在pch里面 #import "Masonry.h"
如果是用的Cocoapods，那就使用#improt <Masonry.h>

**Comment by wosta** [comment]
你好，像第三方输入法textField弹不上来，是怎么回事呢？

**Comment by saitjr** [comment]
我的锅，获得键盘高度的方法错了，把 `ViewController4` 52 行中的 `UIKeyboardFrameBeginUserInfoKey` 改成  `UIKeyboardFrameEndUserInfoKey` 即可。Begin 获取的高度不够。

谢谢
